library(shiny)
shinyUI(
    pageWithSidebar(
        headerPanel("Wiki refer-O-meter"),
        
        sidebarPanel(
            
            h3("Wikipedia referring page calculator"),
            
            p("This app calculates the number of referring Wikipedia pages to a specified Wikipedia article. 
              The app utilizes the Wikipedia \"Special:WhatLinksHere\" application. The Wikipedia listing for a 
              certain article is then scraped by this app and the number of references are sent for subsequent 
              processing."),
            br(),
            
            h4("Find references for a custom article"),
            
            p("Type an expression to find the related article on Wikipedia. After hitting the submit button, 
              the app will check if the an article about the expression exists and finds the number of referring
              pages. The results are displayed on the right panel. Please note that some articles to which several 
              pages are referring require some seconds to obtain the results."),
            
            textInput(inputId = "singleIP", label = "Expression: "),
            actionButton("singleSubmit", "Submit"),
            br(),
            br(),
            br(),
            
            h4("Distribution of reference numbers on Wikipedia"),
            
            p("This algorithm extracts the number of referring pages to random Wikipedia articles. The random 
              Wikipedia articles are generated by the \"Special:Random\" application of Wikipedia. Select or type 
              the desired number of iteration which collects the number of refererences to a random article. 
              The algorihm generates the histogram of the reference numbers summarizing the frequency of reference 
              numbers. The plot is printed on the right panel. Please note that the running time can be several 
              minutes (or more) if high iteration number is specified (> 500)."),
            
            numericInput(inputId = "randomIP", label = "No. of cycles: ",
                         value = 100,
                         min = 0,
                         max = 20000,
                         step = 1),
            actionButton("randomSubmit", "Submit")
        ),
        
        mainPanel(
            
            a("Don't forget to donate to Wikimedia Foundation to maintain Wikipedia!",
            href = "https://donate.wikimedia.org/"),
            br(),
            
            h3("References to a custom Wikipedia article"),
            p("Sumbit an expression on the right panel to obtain the number of referring pages to its 
              Wikipedia article. Please be patient, getting the result may take some time."),
            textOutput("singleOP"),
            tags$head(tags$style("#singleOP{ 
                                 color: red;
                                 font-size: 16px;
                                 }")
                      ),
            br(),
            br(),
            
            h3("Distribution of the number of referring pages on Wikipedia"),
            
            p("Sumbit an iteration number on the left panel to obtain and plot the number of referring pages 
              to random Wikipedia articles. Please be patient, obtaining the result might take some minutes."),
            htmlOutput("randomOP")
        )
    )
)